# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    # GH Actions
    - repo: https://github.com/python-jsonschema/check-jsonschema
      rev: '0.31.2'
      hooks:
          - id: check-github-workflows

    # Quality
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.9
      hooks:
          - id: ruff
            types_or: [python, pyi, jupyter]
            args: [--fix]
          - id: ruff-format
            types_or: [python, pyi, jupyter]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.15.0'
      hooks:
          - id: mypy
            args: [--no-strict-optional, --ignore-missing-imports]
            # NOTE: you might need to add some deps here:
            additional_dependencies: []

    # License Metadata
    - repo: https://github.com/citation-file-format/cff-converter-python
      rev: '054bda51dbe278b3e86f27c890e3f3ac877d616c'
      hooks:
          - id: validate-cff
    - repo: https://github.com/fsfe/reuse-tool
      rev: 'v5.0.2'
      hooks:
          - id: reuse

    # Project Metadata
    - repo: https://github.com/Materials-Data-Science-and-Informatics/somesy
      rev: 'v0.7.1'
      hooks:
          - id: somesy

    # Various general + format-specific helpers
    # (run last to fix general syntactic defects)
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          # - id: mixed-line-ending
          #   args: [--fix=lf]
          - id: check-symlinks
          - id: trailing-whitespace
            exclude: 'CITATION.cff'
          - id: check-yaml
            exclude: 'mkdocs.yml'
          - id: check-toml
          - id: check-json
          - id: check-ast
          - id: debug-statements
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-added-large-files
            args: [--maxkb=10000]
