# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  # Various general + format-specific helpers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-symlinks
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: check-yaml
      exclude: "mkdocs.yml"
    - id: check-toml
    - id: check-json
    - id: check-ast
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-added-large-files
      args: [--maxkb=10000]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: '0.22.0'
    hooks:
    - id: check-github-workflows
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/ambv/black
    rev: '23.1.0'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake

  # Quality
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        additional_dependencies:
          - Flake8-pyproject==1.2.3
          - flake8-docstrings==1.7.0
          - flake8-bugbear==23.3.23
          - dlint==0.14.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        # NOTE: you might need to add some deps here:
        additional_dependencies: []
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
    - id: bandit
      args: ["-q", "-c", "pyproject.toml"]
      additional_dependencies: [ ".[toml]" ]

  # Metadata
  - repo: https://github.com/citation-file-format/cff-converter-python
    rev: '44e8fc9'
    hooks:
      - id: validate-cff
  - repo: https://github.com/fsfe/reuse-tool
    rev: 'v1.1.2'
    hooks:
      - id: reuse
  - repo: local
    hooks:
      - id: update-codemeta
        name: update-codemeta
        language: python
        additional_dependencies: ["rdflib==6.3.1", "codemetapy==2.4.1"]
        entry: update-codemeta codemeta.json
        files: ^pyproject.toml$
